spring:
  profiles:
    active: dev
camel.springboot.shutdownTimeout: 2

---

spring:
  profiles: dev

startRoute: timer:Hola mundo?period=10s
fromRoute : file:data/input?delete=true&readLock=none
toRoute1: file:data/output

message: DEV Environment

---
spring:
  profiles: stage

startRoute: timer:Hola mundo?period=10s
fromRoute : file:data/input?delete=true&readLock=none
toRoute1: file:data/output

message: STAGE Environment

---
spring:
  profiles: prod

startRoute: timer:Hola mundo?period=10s
fromRoute : file:data/input?delete=true&readLock=none
toRoute1: file:data/output


message: PROD Environment
---
spring:
  profiles: mock

startRoute: direct:input
#fromRoute : file:data/input?delete=true&readLock=none
toRoute1: mock/output


message: MOCK Environment
---
